### ISSUE TITLE
Generic rest-api module

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/commander#29]
Since the vision for the node is to be a dump witness creating DB we would like to generalize it as much as possible. 
Right now the only 2 parts that aren't generic enough are the API's and the contract interactions. 

This issue is to discuss how to make the API's and CMD's as generic as possible.

**Comment by vaibhavchellani** [comment]
Right now the midway that I am implementing is as follows:
1. Query a Tx template for txType
2. Fill the parameters in and send the payload along with txType
3. API returns the signBytes
4. The client sends another request with payload and signature.

**Comment by vaibhavchellani** [comment]
We can close this issue because the API's do not need to be built on the node at all.

**Comment by barryWhiteHat** [comment]
How do we get user balance if not asking the node?

**Comment by vaibhavchellani** [comment]
Node will return the accountBytes and the decoding will be done at another abstract layer.
